apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: storm
spec:
  version: {{ .TagName }}
  homepage: https://github.com/guilhem/kubectl-storm
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-storm
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-storm
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-storm
  shortDescription: Monitor and diff excessive generation changes.
  description: |
    Monitor and diff excessive generation changes.
    It detects rapid updates to Kubernetes resource generations, providing detailed diffs and a visual interface for debugging.
    The tool supports filtering by resource types and employs a user-friendly terminal interface to display updates and differences, making it easier to identify and address potential issues caused by high-frequency changes in resource configurations.
