apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: storm
spec:
  version: {{ .TagName }}
  homepage: https://github.com/guilhem/kubectl-storm
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-storm
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-storm
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-storm
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/guilhem/kubectl-storm/releases/download/{{ .TagName }}/kubectl-storm_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-storm
  shortDescription: Monitor and diff excessive Kubernetes resource changes.
  description: |
    Monitor and diff excessive Kubernetes resource changes.
    By default it detects rapid metadata.resourceVersion updates, including status and metadata write storms.
    It can also monitor metadata.generation changes to focus on spec updates.
    The tool supports resource include/exclude filters and uses a terminal interface to display affected resources, change counts, and cleaned diffs.
